version: 2
updates:
  - package-ecosystem: docker
    directory: /docker
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps(docker): "

  - package-ecosystem: github-actions
    directory: "/"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(actions): "
    groups:
      docker:
        patterns:
          - "docker*"
      gcp:
        patterns:
          - "google-github-actions*"
      others:
        patterns:
          - "*"
