version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(actions) "
    groups:
      docker:
        patterns:
          - "docker*"
      gcp:
        patterns:
          - "google-github-actions*"
      linting:
        patterns:
          - "super-linter*"
      others:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: monthly
    commit-message:
      prefix: "deps(docker) "
